trigger:
  branches:
    include:
      - master
      - dev
  paths:
    include:
      - src/*
      - azure-pipelines.yml

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: "windows-latest"

variables:
- group: simplic-deployment
- group: simplic-deployment-dev02
- group: simplic-chocolatey
- name: buildConfiguration
  value: "Debug"

resources:
  repositories:
    - repository: infrastructure
      type: github
      name: simplic/build-infrastructure
      endpoint: simplic-bot

steps:
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: "5.x"

  - task: NuGetCommand@2
    inputs:
      command: "restore"
      restoreSolution: "src/**/*.sln"
      feedsToUse: "select"
      vstsFeed: "f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e"

  - ${{ if not(eq(variables['Build.Reason'], 'PullRequest')) }}:
      - template: version-number-update-token-template.yml@infrastructure
        parameters:
          connection_string: $(connection_string)
          git_user: $(git_user)
          git_token: $(git_token)
          branch_name: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}

  - task: MSBuild@1
    inputs:
      solution: "src/**/*.sln"
      configuration: "$(buildConfiguration)"

  - task: VSTest@2
    inputs:
      testSelector: "testAssemblies"
      testAssemblyVer2: |
        **\Simplic.Package.Test.dll
        !**\obj\**
      searchFolder: "src"

  - task: NuGetCommand@2
    inputs:
      command: "pack"
      packagesToPack: "src/Simplic.**/*.csproj;!src/Simplic.**/*.Test.csproj"
      configuration: "$(buildConfiguration)"
      versioningScheme: "off"

  - task: NuGetCommand@2
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    inputs:
      command: "push"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/Simplic.*.nupkg;!$(Build.ArtifactStagingDirectory)/Simplic.*.symbols.nupkg"
      nuGetFeedType: "internal"
      publishVstsFeed: "f7087ef5-bf6f-48b2-8b8b-5e513f4a7a9e"
      allowPackageConflicts: true

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'New-Item -Path ''$(Build.ArtifactStagingDirectory)\package'' -ItemType Directory'

  - task: ChocolateyCommand@0
    inputs:
      command: 'pack'
      debug: true
      verbose: true
      trace: true
      packOperation: 'single'
      packWorkingDirectory: '$(Build.Repository.LocalPath)'
      packNuspecFileName: 'simpack.nuspec'
      packVersion: '$(Build.BuildNumber)'
      packOutputDirectory: '$(Build.ArtifactStagingDirectory)\package'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\package'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: ChocolateyCommand@0
    inputs:
      command: 'push'
      debug: true
      verbose: true
      trace: true
      pushOperation: 'single'
      pushWorkingDirectory: '$(Build.ArtifactStagingDirectory)\package'
      pushNupkgFileName: 'simpack.$(Build.BuildNumber).nupkg'
      chocolateySourceType: 'manual'
      pushApikey: 'choco_apikey'
