using Simplic.Package.Service;
using System.Linq;
using System.Text;
using Unity;
using Xunit;

namespace Simplic.Package.Test.Unpack
{
    public class UnpackGridServiceTest
    {
        private readonly string json = @"{
    'ReloadGridButtonVisibility': 2,
    'Name': 'Grid_Project',
    'Id': '087cdad0-6331-4908-b5b4-a236816276cf',
    'Profiles': [
        {
            'ProfileName': 'Standardprofil',
            'DisplayIndex': 0,
            'RequiredRole': null,
            'SearchConfiguration': null,
            'DocumentViewerName': 'default',
            'IsDefault': true,
            'ShowNumerationColumn': false,
            'UseSelectColumn': true,
            'ColumnConfiguration': [
                {
                    'GridCellSqlHighlights': [],
                    'UseForUniqueFiltering': false,
                    'SplitCharacter': null,
                    'AggregationFunctions': [],
                    'Id': '30c24eb4-198b-475b-a161-a94dc3f80210',
                    'AggregationText': null,
                    'IsActive': true,
                    'DisplayName': 'Nr.',
                    'InternName': 'Number',
                    'TextAlignment': 1,
                    'TextWrapping': 1,
                    'DefaultWidth': 0.0,
                    'MaxWidth': 0.0,
                    'MinWidth': 0.0,
                    'DefaultGroupIndex': null,
                    'DefaultSorting': null,
                    'FontSize': 11,
                    'FontFamily': 'Segeo UI',
                    'FontStyle': 0,
                    'DisplayIndex': 0,
                    'DataFormatting': null,
                    'DivergentColumnType': null,
                    'CustomCellSelector': null,
                    'IsReadOnly': true,
                    'AggregationMode': 0,
                    'AggregationShowMinValue': false,
                    'AggregationShowMaxValue': false,
                    'AggregationShowAvgValue': false,
                    'AggregationShowCountValue': false,
                    'AggregationShowSumValue': false,
                    'IsSearchable': true,
                    'SearchDataType': 1,
                    'ColorColumnName': null
                },
                {
                    'GridCellSqlHighlights': [],
                    'UseForUniqueFiltering': false,
                    'SplitCharacter': null,
                    'AggregationFunctions': [],
                    'Id': 'e1caf5bb-8057-4cdd-9113-10d40ab2a7fd',
                    'AggregationText': null,
                    'IsActive': false,
                    'DisplayName': 'Guid',
                    'InternName': 'Guid',
                    'TextAlignment': 0,
                    'TextWrapping': 1,
                    'DefaultWidth': 0.0,
                    'MaxWidth': 0.0,
                    'MinWidth': 0.0,
                    'DefaultGroupIndex': null,
                    'DefaultSorting': null,
                    'FontSize': 11,
                    'FontFamily': 'Segeo UI',
                    'FontStyle': 0,
                    'DisplayIndex': 10,
                    'DataFormatting': null,
                    'DivergentColumnType': null,
                    'CustomCellSelector': null,
                    'IsReadOnly': true,
                    'AggregationMode': 0,
                    'AggregationShowMinValue': false,
                    'AggregationShowMaxValue': false,
                    'AggregationShowAvgValue': false,
                    'AggregationShowCountValue': false,
                    'AggregationShowSumValue': false,
                    'IsSearchable': false,
                    'SearchDataType': 0,
                    'ColorColumnName': null
                },
                {
                    'GridCellSqlHighlights': [],
                    'UseForUniqueFiltering': false,
                    'SplitCharacter': null,
                    'AggregationFunctions': [],
                    'Id': '29f6b4bd-5ea7-4a94-86cf-d34efe6b59cc',
                    'AggregationText': null,
                    'IsActive': true,
                    'DisplayName': 'Name',
                    'InternName': 'Name',
                    'TextAlignment': 0,
                    'TextWrapping': 1,
                    'DefaultWidth': 0.0,
                    'MaxWidth': 0.0,
                    'MinWidth': 0.0,
                    'DefaultGroupIndex': null,
                    'DefaultSorting': null,
                    'FontSize': 11,
                    'FontFamily': 'Segeo UI',
                    'FontStyle': 0,
                    'DisplayIndex': 20,
                    'DataFormatting': null,
                    'DivergentColumnType': null,
                    'CustomCellSelector': null,
                    'IsReadOnly': true,
                    'AggregationMode': 0,
                    'AggregationShowMinValue': false,
                    'AggregationShowMaxValue': false,
                    'AggregationShowAvgValue': false,
                    'AggregationShowCountValue': false,
                    'AggregationShowSumValue': false,
                    'IsSearchable': true,
                    'SearchDataType': 1,
                    'ColorColumnName': null
                },
                {
                    'GridCellSqlHighlights': [],
                    'UseForUniqueFiltering': false,
                    'SplitCharacter': null,
                    'AggregationFunctions': [],
                    'Id': '5e12b582-c252-4409-9c5f-bc7843e06935',
                    'AggregationText': null,
                    'IsActive': true,
                    'DisplayName': 'Beginn',
                    'InternName': 'StartDate',
                    'TextAlignment': 0,
                    'TextWrapping': 1,
                    'DefaultWidth': 0.0,
                    'MaxWidth': 0.0,
                    'MinWidth': 0.0,
                    'DefaultGroupIndex': null,
                    'DefaultSorting': null,
                    'FontSize': 11,
                    'FontFamily': 'Segeo UI',
                    'FontStyle': 0,
                    'DisplayIndex': 30,
                    'DataFormatting': 'dd.MM.yyyy',
                    'DivergentColumnType': null,
                    'CustomCellSelector': null,
                    'IsReadOnly': true,
                    'AggregationMode': 0,
                    'AggregationShowMinValue': false,
                    'AggregationShowMaxValue': false,
                    'AggregationShowAvgValue': false,
                    'AggregationShowCountValue': false,
                    'AggregationShowSumValue': false,
                    'IsSearchable': true,
                    'SearchDataType': 2,
                    'ColorColumnName': null
                }
            ],
            'Id': '0b103a7d-d807-481f-88eb-6b1f3c621f99',
            'SelectStatement': '',
            'LoadAllData': false,
            'ShouldAutoReload': false,
            'AutoReloadInterval': null,
            'UserSettings': null,
            'IsCustomProfile': false,
            'IsDeactivated': false,
            'EnableGridRefreshOnDataChange': false,
            'ResolveDroppedDataStatement': null,
            'UseHierarchicalGrid': false,
            'HierachicalGridName': null,
            'VirtualGroupDefinitions': [
                {
                    'Name': 'Virtuelle Gruppe'
                }
            ],
            'CollapseAfterExecute': false,
            'SelectedVirtualGroup': null,
            'SelectedColumn': null,
            'ShowColumnFooter': false,
            'CreateClrAPIModelMethod': null,
            'CreateClrAPIModelMethodParameter': null,
            'EnableDrag': false,
            'EnableDrop': false,
            'CustomRowSelector': null,
            'AutoExpandGroups': false,
            'DropDataService': null,
            'RemoveFromDragSrouce': false,
            'EnableStickyGroupHeaders': false,
            'GroupConfigurationJson': 'W10=',
            'VirtualGroups': []
        }
    ],
    'SelectedProfile': {
        'ProfileName': 'Standardprofil',
        'DisplayIndex': 0,
        'RequiredRole': null,
        'SearchConfiguration': null,
        'DocumentViewerName': 'default',
        'IsDefault': true,
        'ShowNumerationColumn': false,
        'UseSelectColumn': true,
        'ColumnConfiguration': [
            {
                'GridCellSqlHighlights': [],
                'UseForUniqueFiltering': false,
                'SplitCharacter': null,
                'AggregationFunctions': [],
                'Id': '30c24eb4-198b-475b-a161-a94dc3f80210',
                'AggregationText': null,
                'IsActive': true,
                'DisplayName': 'Nr.',
                'InternName': 'Number',
                'TextAlignment': 1,
                'TextWrapping': 1,
                'DefaultWidth': 0.0,
                'MaxWidth': 0.0,
                'MinWidth': 0.0,
                'DefaultGroupIndex': null,
                'DefaultSorting': null,
                'FontSize': 11,
                'FontFamily': 'Segeo UI',
                'FontStyle': 0,
                'DisplayIndex': 0,
                'DataFormatting': null,
                'DivergentColumnType': null,
                'CustomCellSelector': null,
                'IsReadOnly': true,
                'AggregationMode': 0,
                'AggregationShowMinValue': false,
                'AggregationShowMaxValue': false,
                'AggregationShowAvgValue': false,
                'AggregationShowCountValue': false,
                'AggregationShowSumValue': false,
                'IsSearchable': true,
                'SearchDataType': 1,
                'ColorColumnName': null
            },
            {
                'GridCellSqlHighlights': [],
                'UseForUniqueFiltering': false,
                'SplitCharacter': null,
                'AggregationFunctions': [],
                'Id': 'e1caf5bb-8057-4cdd-9113-10d40ab2a7fd',
                'AggregationText': null,
                'IsActive': false,
                'DisplayName': 'Guid',
                'InternName': 'Guid',
                'TextAlignment': 0,
                'TextWrapping': 1,
                'DefaultWidth': 0.0,
                'MaxWidth': 0.0,
                'MinWidth': 0.0,
                'DefaultGroupIndex': null,
                'DefaultSorting': null,
                'FontSize': 11,
                'FontFamily': 'Segeo UI',
                'FontStyle': 0,
                'DisplayIndex': 10,
                'DataFormatting': null,
                'DivergentColumnType': null,
                'CustomCellSelector': null,
                'IsReadOnly': true,
                'AggregationMode': 0,
                'AggregationShowMinValue': false,
                'AggregationShowMaxValue': false,
                'AggregationShowAvgValue': false,
                'AggregationShowCountValue': false,
                'AggregationShowSumValue': false,
                'IsSearchable': false,
                'SearchDataType': 0,
                'ColorColumnName': null
            },
            {
                'GridCellSqlHighlights': [],
                'UseForUniqueFiltering': false,
                'SplitCharacter': null,
                'AggregationFunctions': [],
                'Id': '29f6b4bd-5ea7-4a94-86cf-d34efe6b59cc',
                'AggregationText': null,
                'IsActive': true,
                'DisplayName': 'Name',
                'InternName': 'Name',
                'TextAlignment': 0,
                'TextWrapping': 1,
                'DefaultWidth': 0.0,
                'MaxWidth': 0.0,
                'MinWidth': 0.0,
                'DefaultGroupIndex': null,
                'DefaultSorting': null,
                'FontSize': 11,
                'FontFamily': 'Segeo UI',
                'FontStyle': 0,
                'DisplayIndex': 20,
                'DataFormatting': null,
                'DivergentColumnType': null,
                'CustomCellSelector': null,
                'IsReadOnly': true,
                'AggregationMode': 0,
                'AggregationShowMinValue': false,
                'AggregationShowMaxValue': false,
                'AggregationShowAvgValue': false,
                'AggregationShowCountValue': false,
                'AggregationShowSumValue': false,
                'IsSearchable': true,
                'SearchDataType': 1,
                'ColorColumnName': null
            },
            {
                'GridCellSqlHighlights': [],
                'UseForUniqueFiltering': false,
                'SplitCharacter': null,
                'AggregationFunctions': [],
                'Id': '5e12b582-c252-4409-9c5f-bc7843e06935',
                'AggregationText': null,
                'IsActive': true,
                'DisplayName': 'Beginn',
                'InternName': 'StartDate',
                'TextAlignment': 0,
                'TextWrapping': 1,
                'DefaultWidth': 0.0,
                'MaxWidth': 0.0,
                'MinWidth': 0.0,
                'DefaultGroupIndex': null,
                'DefaultSorting': null,
                'FontSize': 11,
                'FontFamily': 'Segeo UI',
                'FontStyle': 0,
                'DisplayIndex': 30,
                'DataFormatting': 'dd.MM.yyyy',
                'DivergentColumnType': null,
                'CustomCellSelector': null,
                'IsReadOnly': true,
                'AggregationMode': 0,
                'AggregationShowMinValue': false,
                'AggregationShowMaxValue': false,
                'AggregationShowAvgValue': false,
                'AggregationShowCountValue': false,
                'AggregationShowSumValue': false,
                'IsSearchable': true,
                'SearchDataType': 2,
                'ColorColumnName': null
            }
        ],
        'Id': '0b103a7d-d807-481f-88eb-6b1f3c621f99',
        'SelectStatement': 'example select statement',
        'LoadAllData': false,
        'ShouldAutoReload': false,
        'AutoReloadInterval': null,
        'UserSettings': null,
        'IsCustomProfile': false,
        'IsDeactivated': false,
        'EnableGridRefreshOnDataChange': false,
        'ResolveDroppedDataStatement': null,
        'UseHierarchicalGrid': false,
        'HierachicalGridName': null,
        'VirtualGroupDefinitions': [
            {
                'Name': 'Virtuelle Gruppe'
            }
        ],
        'CollapseAfterExecute': false,
        'SelectedVirtualGroup': null,
        'SelectedColumn': null,
        'ShowColumnFooter': false,
        'CreateClrAPIModelMethod': null,
        'CreateClrAPIModelMethodParameter': null,
        'EnableDrag': false,
        'EnableDrop': false,
        'CustomRowSelector': null,
        'AutoExpandGroups': false,
        'DropDataService': null,
        'RemoveFromDragSrouce': false,
        'EnableStickyGroupHeaders': false,
        'GroupConfigurationJson': 'W10=',
        'VirtualGroups': []
    },
    'RequiredRole': null,
    'SearchConfiguration': null,
    'SelectedStackId': '7c34528f-7ab0-4bf5-aa86-85760f193106',
    'SelectedMenuFunction': null,
    'MenuFunctions': [
        {
            'Id': '19f1bf19-f5de-4bab-a1a1-d394cee68f11',
            'RightGuid': '00000000-0000-0000-0000-000000000000',
            'DisplayName': 'project_new',
            'NamedEvent': null,
            'IsRowBased': false,
            'IsGridColumnBased': false,
            'DisplayIndex': 0,
            'AddToContextMenu': true,
            'ExecuteOnDoubleClick': false,
            'ScriptName': null,
            'ScriptClass': null,
            'ScriptMethod': null,
            'NameParameterName': null,
            'ValueParameterName': null,
            'SmallIconGuid': 'a84a8efa-0ce7-40ad-8b1f-0bcbb043f157',
            'LargeIconGuid': 'a84a8efa-0ce7-40ad-8b1f-0bcbb043f157',
            'RibbonIconSize': 2,
            'KeyCode1': 97,
            'KeyCode2': 0,
            'KeyCode3': 0,
            'ClrNamespace': 'Simplic.PlugIn.ProjectManagement',
            'ClrClass': 'ProjectApplicationHelper',
            'ClrMethod': 'New',
            'QuickReportName': null,
            'ReportViewerType': 0,
            'PrintReport': false,
            'IsCustomMenuEntry': false,
            'ParentMenuEntry': null
        },
        {
            'Id': '19c1af75-3650-45c3-a436-af7d67967278',
            'RightGuid': '00000000-0000-0000-0000-000000000000',
            'DisplayName': 'project_edit',
            'NamedEvent': null,
            'IsRowBased': true,
            'IsGridColumnBased': false,
            'DisplayIndex': 10,
            'AddToContextMenu': true,
            'ExecuteOnDoubleClick': true,
            'ScriptName': null,
            'ScriptClass': null,
            'ScriptMethod': null,
            'NameParameterName': null,
            'ValueParameterName': null,
            'SmallIconGuid': 'e515860d-8ed0-48f8-8e9a-cf1f8b449d50',
            'LargeIconGuid': 'e515860d-8ed0-48f8-8e9a-cf1f8b449d50',
            'RibbonIconSize': 2,
            'KeyCode1': 94,
            'KeyCode2': 0,
            'KeyCode3': 0,
            'ClrNamespace': 'Simplic.PlugIn.ProjectManagement',
            'ClrClass': 'ProjectApplicationHelper',
            'ClrMethod': 'Edit',
            'QuickReportName': null,
            'ReportViewerType': 0,
            'PrintReport': false,
            'IsCustomMenuEntry': false,
            'ParentMenuEntry': null
        },
        {
            'Id': '9e706205-8bef-43b1-aca8-ff96f6edd97d',
            'RightGuid': '00000000-0000-0000-0000-000000000000',
            'DisplayName': 'project_open_filestructure',
            'NamedEvent': null,
            'IsRowBased': true,
            'IsGridColumnBased': false,
            'DisplayIndex': 20,
            'AddToContextMenu': true,
            'ExecuteOnDoubleClick': false,
            'ScriptName': null,
            'ScriptClass': null,
            'ScriptMethod': null,
            'NameParameterName': null,
            'ValueParameterName': null,
            'SmallIconGuid': 'dfb01da2-bbe5-4d89-86bd-6a2b19a3b82c',
            'LargeIconGuid': 'dfb01da2-bbe5-4d89-86bd-6a2b19a3b82c',
            'RibbonIconSize': 2,
            'KeyCode1': 0,
            'KeyCode2': 0,
            'KeyCode3': 0,
            'ClrNamespace': 'Simplic.FileStructure.UI.Helper',
            'ClrClass': 'ApplicationHelper',
            'ClrMethod': 'OpenFileStructureEditor',
            'QuickReportName': null,
            'ReportViewerType': 0,
            'PrintReport': false,
            'IsCustomMenuEntry': false,
            'ParentMenuEntry': null
        }
    ],
    'ExportId': '00000000-0000-0000-0000-000000000000',
    'ProfilesToDelete': []
}";

        [Fact]
        public void DeserializeObject_Deserialization_Test()
        {
            var container = new UnityContainer();
            container.RegisterType<IUnpackObjectService, UnpackGridService>();
            container.RegisterType<IFileService, FileService>();

            // var fileService = container.Resolve<IFileService>();
            // var x = await fileService.ReadAllTextAsync("C:\Users\Froehlich\Desktop\blab.txt");

            var unpackObjectResult = new UnpackObjectResult
            {
                Data = Encoding.Default.GetBytes(json),
                Location = ""
            };

            var service = container.Resolve<IUnpackObjectService>();
            var installableObject = service.DeserializeObject(unpackObjectResult);

            Assert.IsType<DeserializedGrid>(installableObject.Content);
            var deserializedGrid = (DeserializedGrid)installableObject.Content;

            // Check if it was properly deserialized for some examples
            Assert.Single(deserializedGrid.Profiles);
            Assert.Equal(4, deserializedGrid.Profiles[0].ColumnConfiguration.Count());
            Assert.Equal("Virtuelle Gruppe", deserializedGrid.SelectedProfile.VirtualGroupDefinitions[0].Name);
            Assert.Null(deserializedGrid.SelectedProfile.SelectedVirtualGroup);

            //var serializedGrid = JsonConvert.SerializeObject(deserializedGrid);
            // var originalDict = JsonConvert.DeserializeObject<Dictionary<string, object>>(json);
            // var afterSerialationDict = JsonConvert.DeserializeObject<Dictionary<string, object>>(serializedGrid);
            // Assert.Equal(originalDict.Count(), afterSerialationDict.Count());
        }
    }
}